#version 430 core

/* Multiplies two matrices. */

layout(local_size_x = 16, local_size_y = 16) in;

layout(std430, binding = 0) readonly  buffer BufA { float A[]; };
layout(std430, binding = 1) readonly  buffer BufB { float B[]; };
layout(std430, binding = 2) writeonly buffer BufC { float C[]; };

uniform int uM; /* Output rows. */
uniform int uN; /* Output columns. */
uniform int uK; /* Sum length. */

/* Computes one output value. */
void main()
{
    int j = int(gl_GlobalInvocationID.x);
    int i = int(gl_GlobalInvocationID.y);

    /* Ignore excess invocations. */
    if (i >= uM || j >= uN)
        return;

    float acc = 0.0;
    for (int k = 0; k < uK; ++k)
        acc += A[i * uK + k] * B[k * uN + j];

    C[i * uN + j] = acc;
}
