#version 430 core
layout(local_size_x = 16, local_size_y = 16) in;
layout(std430, binding = 0) readonly buffer BufA { float A[]; };
layout(std430, binding = 1) readonly buffer BufB { float B[]; };
layout(std430, binding = 2) writeonly buffer BufC { float C[]; };
uniform int uM;
uniform int uN;

void main()
{
    int column = int(gl_GlobalInvocationID.x);
    int row = int(gl_GlobalInvocationID.y);
    if (row >= uM || column >= uN) return;
    int index = row * uN + column;
    C[index] = A[index] - B[index];
}
